
// import hortor from '../hortor/sdk_out';
// let conf = hortor.config;
// let sdk_out = hortor.sdk;
// let crossSDK = hortor.cross;

// const sdk_out = require("../hortor-sdk/sdk.min.js");
// const conf = require('../hortor-sdk/sdk-conf.js');
// const crossSDK = require('../dist/cross-sdk.js');
cc.Class({
    extends: cc.Component,
    properties: {
        tipLabel:cc.Label,
        _stateStr:'',
        _progress:0,
        _splash:null,
        _isLoading:false,
        progressBar1 :{
            type : cc.Node,
            default : null
        },

    },
    

    // use this for initialization
    onLoad: function () {
        // console.log("onLoad");
        // sdk_out.init(conf);  
        // hortor.init(conf); 
    },
    
    start:function(){      
        console.log("........start......");
        var self = this;
        // cc.HQ = {};
        // cc.HQ.WechatApi = require('WechatApi');
        // this.initMgr();
        // this.startPreloading();

        // cc.HQ.WechatApi.wxlogin();
        // console.log(cc.HQ.WechatApi.phoneInfo.windowHeight,"高度高度");

        // // 登录完成后回调
        // var loginCallback = function(data, err)  {
        //     if (data) {
        //         console.log('登录成功！', data);
                
        //         // //区域检测
        //         // sdk_out.checkIP('interfaceId', callback);
        //         // // 示例 ip 后端会根据请求自动判断
        //         // sdk_out.checkIP( function(result) {
        //         //     // 检测结果 result，true 可访问，false 不可访问
        //         //     console.log('checkIP result: ', result);
        //         // });

        //         // var data_json = JSON.parse(data);
        //         cc.HQ.PlayerMgr.info = data.userInfo;
        //         // console.log(cc.HQ.PlayerMgr.info,"jkkkkkkkkkkkkkkkkkkkkkkkkkkkkk");
        //         // sdk.init({
        //         //     debug: true,         //.是否开启调试
        //         //     // userid: cc.HQ.PlayerMgr.info.uid
        //         // }, (res)=>{
        //         //     // sdk.onShareAppMessage({type: 0 });
        //         //     // cc.director.loadScene("Game");  
        //         // });
        //         // var openId = data.userInfo.userId3;
        //         // var userId = data.userInfo.userId;
        //         // var sex = data.userInfo.userSex;
        //         // console.log(data.userInfo,openId,userId,sex);

        //         let config = {
        //             gameId: 'yxcm',             // 必填，游戏ID；
        //             gameVersion: '1.6.1',  // 必填，游戏版本号；
        //             env: 'Prod',                 // 必填，当前环境 测试 Test 上线 Prod
        //             openId: data.userInfo.userId3,              // 必填，登录成功后获取到的用户openId；
        //             userId: data.userInfo.userId,               // 可选，调用平台SDK登录成功后获取的 userId；
        //             sex: data.userInfo.userSex,                        // 必填，0 位置，1 男，2 女；
        //         }
        //         crossSDK.init(config);

                
        //         // sdk.getShareInfo(shareTicket, function(data, err) {
        //         //     if (err) {
        //         //         console.log('获取分享信息失败！',err);
        //         //     } else if (data) {
        //         //         console.log('获取分享信息成功！',data);
        //         //     }
        //         // })


        //         // 监听右上角分享
        //         // sdk_out.onShareAppMessage(()=>{
        //         //     // console.log("wwwwwwwwwwwwwwwwwhat");
        //         //     return {
        //         //         title: '不要怂，全梭哈！赢了会所嫩模，输了下海干活！',
        //         //         query: 'shareConfigId=xxx',
        //         //         imageUrl: "https://res.g.llewan.com/uploadfile/houtai/share/20180907/20180907134633_8749.png",
        //         //     }
        //         //     // return shareObj;
        //         // })

        //         // sdk_out.checkIP({
        //         //     interfaceId: 'default',  // 可选，默认default，运营反馈的 接口ID
        //         //     // userId: data.userInfo.userId,
        //         //     callback: function(result) {
        //         //         // 检测结果 result，true 可访问，false 不可访问
        //         //         console.log('checkIP result: ', result);
        //         //         cc.director.loadScene("Game");
        //         //     }
        //         // });

        //         cc.director.loadScene("Game");
        //         // console.log('checkIP result: 》》》》》');
                
        //     }
            
        //     else if (err) console.log('登录失败！',err)
        // }
        // // 授权按钮配置
        // var btnConfig = {
        //     config: { // 授权按钮样式
        //         type: 'image',
        //         image: 'https://caveman-test-resource.hortorgames.com/resource/btn_enter.png',
        //         style: { width: 200, height: 70, top: (cc.HQ.WechatApi.phoneInfo.windowHeight-70)/2, left: (cc.HQ.WechatApi.phoneInfo.windowWidth-200)/2 }
        //     },
        //     onShow: function() { // 授权按钮展示回调
        //         console.log('授权按钮展示')
        //     },
        //     onTap: function(data, err) { // 授权按钮点击回调
        //         if (data) console.log('授权成功！')
        //         else if (err) console.log('拒绝授权！')
        //     }
        // }
        // 开始登录
        // sdk_out.decodeLogin(loginCallback, btnConfig);

        sdk.WeChatLoginNoAuth((user_msg)=>{
            console.log("用户信息：", user_msg);
            // self.user = user_msg;
            game_msg.openid = user_msg.openid;
            banner_fn5();
            sdk.getFromServer("GameMsg","Json",null,(d)=>{
                if(d){
                    var aProps = Object.getOwnPropertyNames(d);
                    // var bProps = Object.getOwnPropertyNames(quju_global);
                    for (var i = 0; i < aProps.length; i++) {
                        var propName = aProps[i];
                        // if(d[propName] != null){
                            game_msg[propName] = d[propName];
                        // }    
                    }
                }
                game_msg.houtai_kaiguan = false;
                var d = sdk.getConfig1();
                if(d && d.hz == 1){
                    game_msg.houtai_kaiguan = true;
                }
                var d2 = sdk.getConfig2();
                // console.log("运营配置信息2", d2);
                if(d2 && d2.share_tip){
                    game_msg.share_tip = d2.share_tip;
                }
                cc.director.loadScene("Game");
            })
        })

        // 右上角分享
        sdk.onShareAppMessage({type: 0 });
    },
    
    // initMgr:function(){
    //     cc.HQ = {};//这是全局的公众变量
    //     //公共文件
    //     cc.HQ.Global = require("Global");
    //     cc.HQ.net = require("Net");
    //     var NetMgr = require("NetMgr");
    //     cc.HQ.netMgr = new NetMgr();
    //     cc.HQ.netMgr.init();
    //     // cc.HQ.netMgr.setDataEventHandler(this.node);
    //     cc.HQ.netMgr.dataEventHandler=this.node;
    //     cc.HQ.PlayerMgr = require("PlayerMgr");
    //     //游戏中默认开启声音
    //     cc.HQ.soundMgr = require("SoundManage");
    //     cc.HQ.soundMgr.setAudio(true);
    //     //记录声音选择的状态(开启或关闭) 用个全局变量cc.HQ.suoundState来控制
    //     cc.HQ.suoundState =true;
    //     //微信接口
    //     cc.HQ.WechatApi = require('WechatApi');

    //     cc.HQ.WechatApi.showShareMenu();
        
    //     this.onSetNode();
    // },

    
    // startPreloading:function(){
    //     this._stateStr = "加载中，请稍候";  
    //     this._isLoading = true;
    //     var that =this;
        
    //     cc.loader.onProgress = function ( completedCount, totalCount,  item ){
    //         if(that._isLoading){
    //             console.log("结果",completedCount/totalCount);
    //             that._progress = completedCount/totalCount;
    //             // that.tipLabel.string =(that._progress * 100).toFixed(0);
    //             if(that.progressBar1)that.progressBar1.getComponent(cc.ProgressBar).progress=that._progress;
    //         }
    //     };
    // },
    
    // onLoadComplete:function(){
    //     this._isLoading = false;
    //     this._stateStr = "准备登陆";
    //     cc.loader.onComplete = null;
    // },

    // called every frame, uncomment this function to activate update callback
    update: function (dt) {
        // if(this._stateStr.length == 0){
        //     return;
        // }
        // this.tipLabel.string = this._stateStr + ' ';
        // if(this._isLoading){
        //     this.tipLabel.string += Math.floor(this._progress * 100) + "%";   
            
        // }
        // else{
        //     var t = Math.floor(Date.now() / 1000) % 4;
        //     for(var i = 0; i < t; ++ i){
        //         this.tipLabel.string += '.';
        //     }            
        // }
    },

    //监听事件
    onSetNode:function(){
        // this.node.on('login_bak',function(data){
        //     //console.log("监听要执行的事件!!!",data,data.detail.code,this.tipLabel.string);
        //     // cc.HQ.WechatApi.getUser(data.detail);
        //     // cc.HQ.WechatApi.getUser(data);

        //     // console.log(cc.HQ.PlayerMgr.info.uid,"................................");
            

        // }.bind(this));

        // this.node.on('open_bak',function(data){
        //     console.log("node:open_bak",data,data.detail);
        //     // if(data.detail.code==1){
        //     if(data.code==1){
        //         console.log("长连接成功");
        //         // this.tipLabel.node.active =true;  //点击了获取信息按钮后，才显示加载信息
        //         // cc.HQ.WechatApi.set_sub_info();
        //         // cc.director.loadScene("Game");

        //     }else{
        //         console.log("长连接失败");
        //         // cc.HQ.net.reconnect();
        //     }
        //     //cc.director.loadScene("Game");
        // }.bind(this));
        
        //监听所有出错的事件回调
        // this.node.on('error_bak',function(data){
        //     console.log("error_bak:",data);
        // });

        //监听用户信息的更新

        // this.node.on('user_info_mod_bak',function(data){
        //     console.log("user_info_mod_bak:",data);
        // });
    },

});